#!/usr/bin/env bash
#==============================================================================
# Convert txt to html via pandoc
#==============================================================================
BASE=$(cd $(dirname $0); pwd)

# options
OPT="-f markdown+autolink_bare_uris+abbreviations -sS --toc --webtex"

# stylesheet
CSS="$BASE/typography.css"
if [ -f "$CSS" ]; then
    CSS=" -c $CSS"
else
    CSS=""
fi

# bibliography
BIB="$HOME/Documents/Mendeley/library.bib"
if [ -f "$BIB" ]; then
    BIB=" --bibliography='$BIB'"
else
    BIB=""
fi

if [[ -f "$1" ]]; then
    TEXT=$(cat $1)
    shift
else
    # get text from stdin
    read -rd '' TEXT
fi

# pre process
if [[ -f "$BASE/pre_processor" ]]; then
    TEXT=$(echo -nE "$TEXT" | bash $BASE/pre_processor)
fi

# convert the text with pandoc
TEXT=$(echo -nE "$TEXT" | pandoc $OPT $CSS $BIB $@)

# post process
if [[ -f "$BASE/post_processor" ]]; then
    TEXT=$(echo -nE "$TEXT" | bash $BASE/post_processor)
fi

# output the results
echo -nE "$TEXT"
echo
