#!/usr/bin/env bash
REMOTE_FORWARD=2022

if [[ -n "$REMOTEHOST$SSH_CONNECTION" ]]; then
    # Use remote forward to execute 'clip' command in remote server
    # ~/.ssh/config
    #
    # Host examplehost
    #   Hostname xxx.xxx.xxx.xxx
    #   Port 22
    #   User xxxxx
    #   RemoteForward 2022 localhost:22
    #
    ssh localhost -p $REMOTE_FORWARD clip $@
else
    if command -v xclip 1>/dev/null; then
        if [[ -n $1 ]]; then
            echo "$1" | xclip -selection clipboard
        elif [[ -p /dev/stdin ]]; then
            xclip -i -selection clipboard
        else
            xclip -o -selection clipboard
        fi
    elif command -v pbcopy 1>/dev/null; then
        if [[ -n $1 ]]; then
            echo "$1" | pbcopy
        elif [[ -p /dev/stdin ]]; then
            pbcopy
        else
            pbpaste
        fi
    fi
fi
