# Default Theme

#if patched_font_in_use; then
#	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮂"
#	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="⮃"
#	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="⮀"
#	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="⮁"
#else
#	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
#	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
#	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
#	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
#fi
TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="||"
TMUX_POWERLINE_SEPARATOR_LEFT_THIN="|"
TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="||"
TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="|"

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"hostname 67 235" \
		"lan_ip 235 60" \
		"wan_ip 235 66" \
		"now_playing 235 102" \
		"np_itunes 235 102" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"tmux_mem_cpu_load 235 66" \
		"ifstat_sys 235 64" \
		"battery 235 127" \
		"weather 235 72" \
		"date 235 75" \
		"time 235 75" \
	)
fi
