# Default Theme
TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
TMUX_POWERLINE_SEPARATOR_LEFT_THIN="|"
TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="|"

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=""
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=""

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=235
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=255

TMUX_POWERLINE_SEG_DATE_FORMAT=" %a %d/%m"
TMUX_POWERLINE_SEG_TIME_FORMAT="%H:%M"

# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"sessioninfo 60 234" \
		"lan_ip 235 60" \
		"wan_ip 235 66" \
		"now_playing 235 102" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"weather 235 72" \
		"battery 235 127" \
		"hostname 65 235" \
	)
fi
