[[plugins]]
repository = 'Shougo/neobundle.vim'
fetch = 1

[[plugins]]
repository = 'Shougo/vimproc.vim'
build_commands = 'make'
build = 'make'

[[plugins]]
repository = 'vim-jp/vimdoc-ja'

# Fundemental -----------------------------------------------------------------
[[plugins]]
external_commands = 'sudo'
repository = 'sudo.vim'

[[plugins]]
repository = 'cohama/vim-hier'

[[plugins]]
repository = 'thinca/vim-template'

[[plugins]]
repository = 'lambdalisue/vim-diffa'

[[plugins]]
repository = 'powerman/vim-plugin-AnsiEsc'
on_cmd = 'AnsiEsc'

[[plugins]]
repository = 'osyo-manga/vim-over'
on_cmd = [
    'OverCommandLine',
    'OverCommandLineNoremap',
]

[[plugins]]
repository = 'kana/vim-repeat'
on_map = '<Plug>'

[[plugins]]
repository = 't9md/vim-quickhl'
depends = 'kana/vim-operator-user'
on_map = [
    '<Plug>',
    '<Plug>(operator-quickhl-manual'
]

[[plugins]]
repository = 'tyru/open-browser.vim'
on_map = '<Plug>'

[[plugins]]
gui = 1
repository = 'lambdalisue/vim-fullscreen'
on_map = '<Plug>'

[[plugins]]
repository = 'rhysd/clever-f.vim'
on_map = '<Plug>'

[[plugins]]
repository = 'haya14busa/incsearch.vim'
on_map = '<Plug>'

[[plugins]]
repository = 'haya14busa/vim-asterisk'
on_map = '<Plug>'
on_source = 'incsearch.vim'

[[plugins]]
repository = 'LeafCage/yankround.vim'
on_map = '<Plug>'

[[plugins]]
repository = 'tyru/capture.vim'
on_cmd = 'Capture'

[[plugins]]
repository = 'MattesGroeger/vim-bookmarks'
depends = 'Shougo/unite.vim'
augroup = 'bm_vim_enter'
on_map = '<Plug>'
on_source = 'unite.vim'

[[plugins]]
repository = 'thinca/vim-quickrun'
on_map = '<Plug>'
on_cmd = 'QuickRun'

[[plugins]]
repository = 'thinca/vim-qfreplace'
on_source = ['unite.vim', 'vimfiler.vim']
on_cmd = 'Qfreplace'

[[plugins]]
repository = 'AndrewRadev/switch.vim'
on_cmd = 'Switch'

[[plugins]]
repository = 'AndrewRadev/linediff.vim'
on_cmd = 'Linediff'

[[plugins]]
repository = 'kurkale6ka/vim-swap'
on_map = '<Plug>'

[[plugins]]
repository = 'lambdalisue/vim-pager'
on_cmd = 'PAGER'

[[plugins]]
repository = 'lambdalisue/vim-manpager'
on_cmd = ['MANPAGER', 'Man']

[[plugins]]
repository = 't9md/vim-choosewin'
on_map = '<Plug>'

[[plugins]]
repository = 'lambdalisue/vim-findent'
    [[plugins.on_cmd]]
    name = 'Findent'
    complete = 'customlist,findent#FindentComplete'
    [[plugins.on_cmd]]
    name = 'FindentRestore'
    complete = 'customlist,findent#FindentRestoreComplete'

[[plugins]]
repository = 'osyo-manga/vim-trip'
on_map = '<Plug>'

[[plugins]]
repository = 'kana/vim-altr'
on_map = '<Plug>'

[[plugins]]
repository = 'lambdalisue/vim-foldround'
on_map = '<Plug>'

[[plugins]]
repository = 'thinca/vim-zenspace'

[[plugins]]
repository = 'Shougo/junkfile.vim'
on_cmd = 'JunkfileOpen'

[[plugins]]
repository = 'lambdalisue/vim-protocol'
on_path = '\%(^https\?://\|\.zip$\)'

# Completion ------------------------------------------------------------------
[[plugins]]
disabled = "!has('lua')"
repository = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
neovim = 1
repository = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/neco-syntax'
#on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'Shougo/neco-vim'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'Shougo/neoinclude.vim'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
external_commands = 'look'
repository = 'ujihisa/neco-look'
#on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
external_commands = 'ghc-mod'
repository = 'eagletmt/neco-ghc'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'hrsh7th/vim-neco-calc'
#on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = [
    'Shougo/neosnippet-snippets',
    'Shougo/context_filetype.vim',
]
on_source = 'unite.vim'
on_ft = 'snippet'
on_i = 1

[[plugins]]
repository = 'Shougo/echodoc.vim'
on_i = 1


# Statusline ------------------------------------------------------------------
[[plugins]]
repository = 'itchyny/lightline.vim'
depends = 'cocopon/lightline-hybrid.vim'

[[plugins]]
vim_version = '7.4'
repository = 'osyo-manga/vim-watchdogs'
depends = 'Shougo/vimproc.vim'

[[plugins]]
repository = 'dannyob/quickfixstatus'

[[plugins]]
vim_version = '7.4'
repository = 'KazuakiM/vim-qfstatusline'
depends = 'osyo-manga/shabadou.vim'


# Textobj ---------------------------------------------------------------------
[[plugins]]
repository = 'kana/vim-textobj-user'
lazy = 1

[[plugins]]
repository = 'kana/vim-textobj-entire'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'kana/vim-textobj-line'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'kana/vim-textobj-syntax'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'kana/vim-textobj-indent'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'kana/vim-textobj-datetime'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'thinca/vim-textobj-comment'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'saihoooooooo/vim-textobj-space'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'kana/vim-textobj-fold'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'kana/vim-textobj-underscore'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'RyanMcG/vim-textobj-dash'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'mattn/vim-textobj-url'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'sgur/vim-textobj-parameter'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
repository = 'rhysd/vim-textobj-word-column'
depends = 'kana/vim-textobj-user'
on_map = [['ox', '<Plug>']]

[[plugins]]
external_commands = 'python'
repository = 'bps/vim-textobj-python'
depends = 'kana/vim-textobj-user'
#on_ft = ['python', 'python3']


# Operator --------------------------------------------------------------------
[[plugins]]
repository = 'kana/vim-operator-user'
lazy = 1

[[plugins]]
repository = 'kana/vim-operator-replace'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repository = 'sgur/vim-operator-openbrowser'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repository = 'rhysd/vim-operator-trailingspace-killer'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repository = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repository = 'lambdalisue/vim-operator-breakline'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>']]

[[plugins]]
repository = 'chikatoike/concealedyank.vim'
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>(operator-concealedyank)']]


# Interface -------------------------------------------------------------------
[[plugins]]
repository = 'ctrlpvim/ctrlp.vim'
lazy = 1

[[plugins]]
repository = 'Shougo/unite.vim'
    [[plugins.on_cmd]]
    name = ['Unite', 'UniteWithCursorWord']
    complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/vimshell.vim'
    [[plugins.on_cmd]]
    name = ['VimShell', 'VimShellTab', 'VimShellPop']
    complete = 'customlist,vimshell#complete'

[[plugins]]
repository = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_path = '\h\w*:'
    [[plugins.on_cmd]]
    name = ['VimFiler', 'VimFilerExplorer']
    complete = 'customlist,vimfiler#complete'

[[plugins]]
repository = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

[[plugins]]
repository = 'thinca/vim-ref'
on_cmd = 'Ref'

[[plugins]]
repository = 'mojako/ref-sources.vim'
#on_source = 'vim-ref'

[[plugins]]
repository = 'majutsushi/tagbar'
augroup = 'TagbarAutoCmds'
on_cmd = ['Tagbar', 'TagbarOpen', 'TagbarToggle']

[[plugins]]
repository = 'glidenote/memolist.vim'
depends = ['Shougo/unite.vim', 'fuenor/qfixgrep']
on_cmd = [
    'MemoNew',
    'MemoList',
    'MemoGrep',
]

[[plugins]]
repository = 'godlygeek/tabular'
on_cmd = 'Tabularize'

[[plugins]]
repository = 'deris/vim-rengbang'
on_cmd = [
    'RengBang',
    'RengBangUsePrev',
    'RengBangConfirm',
]

[[plugins]]
repository = 'lilydjwg/colorizer'
on_map = '<Plug>'
on_cmd = [
    'ColorHighlight',
    'ColorToggle',
]

[[plugins]]
repository = 'itchyny/calendar.vim'
on_cmd = 'Calendar'


# Unite sources ---------------------------------------------------------------
[[plugins]]
repository = 'Shougo/neomru.vim'

[[plugins]]
repository = 'Shougo/neossh.vim'

[[plugins]]
repository = 'Shougo/unite-help'

[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'osyo-manga/unite-quickfix'

[[plugins]]
repository = 'ujihisa/unite-font'

[[plugins]]
repository = 'ujihisa/unite-colorscheme'

[[plugins]]
repository = 'rhysd/unite-codic.vim'

[[plugins]]
repository = 'pasela/unite-webcolorname'

[[plugins]]
repository = 'lambdalisue/unite-linephrase'

[[plugins]]
repository = 'joker1007/unite-pull-request'

[[plugins]]
repository = 'dameninngenn/unite-perldoc'

[[plugins]]
external_commands = 'git'
repository = 'kmnk/vim-unite-giti'

[[plugins]]
repository = 'rafi/vim-unite-issue'
depends = ['mattn/webapi-vim', 'tyru/open-browser.vim']
on_source = 'unite.vim'

[[plugins]]
repository = 'lambdalisue/vim-gista-unite'
depends = ['lambdalisue/vim-gista']
on_source = 'unite.vim'


# Version controller system ---------------------------------------------------
[[plugins]]
external_commands = 'git'
repository = 'lambdalisue/vim-gita'
rev = 'alpha-3'
    [[plugins.on_cmd]]
    name = 'Gita'
    complete = 'customlist,gita#complete'

[[plugins]]
repository = 'lambdalisue/vim-gista'
    [[plugins.on_cmd]]
    name = 'Gista'
    complete = 'customlist,gista#command#complete'

[[plugins]]
repository = 'lambdalisue/vim-gista-ctrlp'
depends = ['lambdalisue/vim-gista', 'ctrlpvim/ctrlp.vim']
on_cmd = 'CtrlPGista'
on_func = 'ctrlp#gista#'

[[plugins]]
external_commands = 'git'
repository = 'cohama/agit.vim'
on_cmd    = ['Agit', 'AgitFile']
on_source = 'unite.vim'


[[plugins]]
disabled = 1
external_commands = 'git'
repository = 'tpope/vim-fugitive'
augroup = 'fugitive'
on_cmd = [
    'Git', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge',
    'Gpull', 'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog',
    'Gllog', 'Gedit', 'Gsplit', 'Gvsplit', 'Gtabedit', 'Gpedit',
    'Gread', 'Gwrite', 'Gwq', 'Gdiff', 'Gsdiff', 'Gvdiff',
    'Gmove', 'Gremove', 'Gblame', 'Gbrowse',
]


# Syntax ----------------------------------------------------------------------
[[plugins]]
repository = 'hail2u/vim-css3-syntax'
#on_ft = ['css', 'sass', 'scss', 'less', 'html']

[[plugins]]
repository = 'othree/html5.vim'
#on_ft = 'html'

[[plugins]]
repository = 'groenewege/vim-less'
#on_ft = 'less'

[[plugins]]
repository = 'cakebaker/scss-syntax.vim'
#on_ft = ['sass', 'scss']

[[plugins]]
repository = 'kchmck/vim-coffee-script'
#on_ft = 'coffeescript'

[[plugins]]
repository = 'elzr/vim-json'
#on_ft = 'json'

[[plugins]]
repository = 'jQuery'
#on_ft = ['javascript', 'coffeescript', 'typescript']

[[plugins]]
repository = 'jelera/vim-javascript-syntax'
#on_ft = ['javascript', 'typescript']

[[plugins]]
repository = 'jason0x43/vim-js-indent'
#on_ft = ['javascript', 'typescript']

[[plugins]]
repository = 'leafgarland/typescript-vim'
#on_ft = 'typescript'

[[plugins]]
repository = 'thinca/vim-ft-help_fold'
#on_ft = 'help'

[[plugins]]
repository = 'vim-scripts/applescript.vim'
#on_ft = 'applescript'

[[plugins]]
repository = 'cespare/vim-toml'
#on_ft = 'toml'

[[plugins]]
repository = 'vim-scripts/indentpython.vim'
#on_ft = ['python', 'python3']

[[plugins]]
repository = 'vim-scripts/python_match.vim'
#on_ft = ['python', 'python3']

[[plugins]]
repository = 'tmhedberg/SimpylFold'
#on_ft = ['python', 'python3']

[[plugins]]
repository = 'vim-perl/vim-perl'
#on_ft = 'perl'


# Specific --------------------------------------------------------------------
[[plugins]]
external_commands = 'latexmk'
repository = 'LaTeX-Box-Team/LaTeX-Box'
on_cmd = 'Latexmk'
on_ft = ['tex', 'plaintex']

[[plugins]]
build_commands = 'pip'
build = 'pip install autopep8'
repository = 'tell-k/vim-autopep8'
#on_ft = ['python', 'python3']

[[plugins]]
build_commands = 'git'
build = 'git submodule update --init'
repository = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3']
on_source = 'vim-pyenv'

[[plugins]]
external_commands = 'pyenv'
repository = 'lambdalisue/vim-pyenv'
on_ft = ['python', 'python3']
on_cmd = 'PyenvActivate'

[[plugins]]
repository = 'hotchpotch/perldoc-vim'
on_ft = 'perl'

[[plugins]]
vim_version = '7.4'
build_commands = 'npm'
build = 'npm install -g typescript'
repository = 'Quramy/tsuquyomi'
depends = 'Shougo/vimproc.vim'
on_ft = 'typescript'

[[plugins]]
repository = 'vim-pandoc/vim-pandoc'
on_ft = 'pandoc'

[[plugins]]
repository = 'kannokanno/previm'
depends = 'tyru/open-browser.vim'
on_cmd = 'PrevimOpen'


# Misc ------------------------------------------------------------------------
[[plugins]]
repository = 'cocopon/colorswatch.vim'
on_cmd = 'ColorSwatchGenerate'


# Vimscript development -------------------------------------------------------
[[plugins]]
repository = 'vim-jp/vital.vim'
on_cmd = 'Vitalize'

[[plugins]]
repository = 'lambdalisue/vital-ArgumentParser'

[[plugins]]
repository = 'haya14busa/vital-power-assert'
depends = ['haya14busa/vital-vimlcompiler']

[[plugins]]
repository = 'thinca/vim-themis'
#on_ft = ['vim', 'vimspec']

[[plugins]]
repository = 'thinca/vim-prettyprint'
on_cmd  = ['PP', 'PrettyPrint']
on_func = ['PP', 'PrettyPrint']

[[plugins]]
repository = 'syngan/vim-vimlint'
depends = 'ynkdir/vim-vimlparser'

[[plugins]]
repository = 'LeafCage/laptime.vim'
#lazy = 1
