[[plugins]]
repository = 'Shougo/neobundle.vim'
fetch = 1

[[plugins]]
repository = 'Shougo/vimproc.vim'
build_commands = 'make'
build = 'make'
lazy = 0

[[plugins]]
repository = 'vim-jp/vimdoc-ja'
lazy = 0

# Fundemental -----------------------------------------------------------------
[[plugins]]
repository = 'sudo.vim'
lazy = 0

[[plugins]]
repository = 'cohama/vim-hier'
lazy = 0

[[plugins]]
repository = 'thinca/vim-template'
lazy = 0

[[plugins]]
repository = 'lambdalisue/vim-diffa'
lazy = 0

[[plugins]]
repository = 'powerman/vim-plugin-AnsiEsc'
lazy = 0

[[plugins]]
repository = 'osyo-manga/vim-over'
lazy = 0

[[plugins]]
repository = 'kana/vim-repeat'
on_map = '<Plug>(repeat-'

[[plugins]]
repository = 't9md/vim-quickhl'
depends = 'kana/vim-operator-user'
on_map = [
    '<Plug>(quick-manual',
    '<Plug>(operator-quickhl-manual'
]

[[plugins]]
repository = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser-'

[[plugins]]
repository = 'lambdalisue/vim-fullscreen'
on_map = '<Plug>(fullscreen-'

[[plugins]]
repository = 'osyo-manga/vim-over'
lazy = 0

[[plugins]]
repository = 'rhysd/clever-f.vim'
on_map = '<Plug>(clever-f-'

[[plugins]]
repository = 'haya14busa/vim-asterisk'
on_map = '<Plug>(asterisk-'
on_source = 'incsearch.vim'
focus = 1

[[plugins]]
repository = 'haya14busa/incsearch.vim'
on_map = '<Plug>(incsearch-'
focus = 1

[[plugins]]
repository = 'LeafCage/yankround.vim'
on_map = '<Plug>(yankround-'

[[plugins]]
repository = 'tyru/capture.vim'
on_cmd = 'Capture'

[[plugins]]
repository = 'MattesGroeger/vim-bookmarks'
depends = 'Shougo/unite.vim'
augroup = 'bm_vim_enter'
on_map = '<Plug>Bookmark'
on_source = 'unite.vim'

[[plugins]]
repository = 'thinca/vim-quickrun'
on_map = '<Plug>(quickrun'

[[plugins]]
repository = 'thinca/vim-qfreplace'
on_source = ['unite.vim', 'vimfiler.vim']
on_cmd = 'Qfreplace'

[[plugins]]
repository = 'AndrewRadev/switch.vim'
on_cmd = 'Switch'

[[plugins]]
repository = 'AndrewRadev/linediff.vim'
on_cmd = ['Linediff', 'LinediffReset']

[[plugins]]
repository = 'kurkale6ka/vim-swap'
on_map = '<Plug>SwapSwap'

[[plugins]]
repository = 'lambdalisue/vim-pager'
on_cmd = 'PAGER'

[[plugins]]
repository = 'lambdalisue/vim-manpager'
on_cmd = ['MANPAGER', 'Man']

#[[plugins]]
#repository = 'cohama/lexima.vim'
#insert = 1

[[plugins]]
repository = 't9md/vim-choosewin'
on_map = '<Plug>(choosewin)'

[[plugins]]
repository = 'lambdalisue/vim-findent'
on_func = 'findent#'
    [[plugins.on_cmd]]
    name = 'Findent'
    complete = 'customlist,findent#FindentComplete'
    [[plugins.on_cmd]]
    name = 'FindentRestore'
    complete = 'customlist,findent#FindentRestoreComplete'

[[plugins]]
repository = 'osyo-manga/vim-trip'
on_map = '<Plug>(trip-'

[[plugins]]
repository = 'kana/vim-altr'
on_func = 'altr#'
on_map = '<Plug>(altr-'

[[plugins]]
repository = 'lambdalisue/vim-foldround'
on_func = 'foldround#'
on_map = '<Plug>(foldround-'

# The following makes things incorrect
#[[plugins]]
#repository = 'Konfekt/FastFold'
#lazy = 0

[[plugins]]
repository = 'thinca/vim-zenspace'
lazy = 0

[[plugins]]
repository = 'Shougo/junkfile.vim'
on_cmd = 'JunkfileOpen'

[[plugins]]
repository = 'lambdalisue/vim-protocol'
lazy = 0

# Completion ------------------------------------------------------------------
[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
on_i = 1
neovim = 1

[[plugins]]
repository = 'Shougo/neco-syntax'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'Shougo/neco-vim'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'Shougo/neoinclude.vim'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'ujihisa/neco-look'
external_commands = 'look'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'eagletmt/neco-ghc'
external_commands = 'ghc-mod'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'hrsh7th/vim-neco-calc'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = [
    'Shougo/neosnippet-snippets',
    'Shougo/context_filetype.vim',
]
on_cmd = [
    'NeoSnippetMakeCache',
    'NeoSnippetEdit',
    'NeoSnippetSource',
    'NeoSnippetClearMarkers',
]
on_source = 'unite.vim'
on_ft = 'snippet'
on_i = 1

[[plugins]]
repository = 'Shougo/echodoc.vim'
on_i = 1


# Statusline ------------------------------------------------------------------
[[plugins]]
repository = 'itchyny/lightline.vim'
depends = 'cocopon/lightline-hybrid.vim'
lazy = 0

[[plugins]]
repository = 'osyo-manga/vim-watchdogs'
depends = 'Shougo/vimproc.vim'
vim_version = '7.4'
lazy = 0

[[plugins]]
repository = 'dannyob/quickfixstatus'
lazy = 0

[[plugins]]
repository = 'KazuakiM/vim-qfstatusline'
vim_version = '7.4'
depends = 'osyo-manga/shabadou.vim'
lazy = 0


# Textobj ---------------------------------------------------------------------
[[plugins]]
repository = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-textobj-entire'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-textobj-line'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-textobj-syntax'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-textobj-indent'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-textobj-datetime'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'thinca/vim-textobj-comment'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'saihoooooooo/vim-textobj-space'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-textobj-fold'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-textobj-underscore'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'RyanMcG/vim-textobj-dash'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'mattn/vim-textobj-url'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'sgur/vim-textobj-parameter'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'rhysd/vim-textobj-word-column'
depends = 'kana/vim-textobj-user'
lazy = 0

[[plugins]]
repository = 'bps/vim-textobj-python'
depends = 'kana/vim-textobj-user'
external_commands = 'python'
on_ft = ['python', 'python3']


# Operator --------------------------------------------------------------------
[[plugins]]
repository = 'kana/vim-operator-user'
lazy = 0

[[plugins]]
repository = 'kana/vim-operator-replace'
depends = 'kana/vim-operator-user'
on_map = '<Plug>(operator-replace'

[[plugins]]
repository = 'sgur/vim-operator-openbrowser'
depends = 'kana/vim-operator-user'
on_map = '<Plug>(operator-openbrowser'

[[plugins]]
repository = 'rhysd/vim-operator-trailingspace-killer'
depends = 'kana/vim-operator-user'
on_map = '<Plug>(operator-trailingspace-killer'

[[plugins]]
repository = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
on_map = '<Plug>(operator-surround'

[[plugins]]
repository = 'lambdalisue/vim-operator-breakline'
depends = 'kana/vim-operator-user'
on_map = '<Plug>(operator-breakline'


[[plugins]]
repository = 'chikatoike/concealedyank.vim'
depends = 'kana/vim-operator-user'
on_map = '<Plug>(operator-concealedyank'

# Make Vim slow
#[[plugins]]
#repository = 'haya14busa/vim-operator-flashy'
#depends = 'kana/vim-operator-user'
#on_map = '<Plug>(operator-flashy'

# Interface -------------------------------------------------------------------
[[plugins]]
repository = 'ctrlpvim/ctrlp.vim'
on_cmd = 'CtrlP'
on_func = 'ctrlp#'

[[plugins]]
repository = 'Shougo/unite.vim'
focus = 1
    [[plugins.on_cmd]]
    name = 'Unite'
    complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/vimshell.vim'
    [[plugins.on_cmd]]
    name = ['VimShell', 'VimShellPop']
    complete = 'customlist,vimshell#complete'

[[plugins]]
repository = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_path = '\h\w*:'
focus = 1
    [[plugins.on_cmd]]
    name = ['VimFiler', 'VimFilerExplorer']
    complete = 'customlist,vimfiler#complete'

[[plugins]]
repository = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

[[plugins]]
repository = 'thinca/vim-ref'
on_cmd = 'Ref'

[[plugins]]
repository = 'mojako/ref-sources.vim'
on_source = 'vim-ref'

[[plugins]]
repository = 'majutsushi/tagbar'
augroup = 'TagbarAutoCmds'
on_cmd = ['Tagbar', 'TagbarToggle']

[[plugins]]
repository = 'glidenote/memolist.vim'
depends = [
    'Shougo/unite.vim',
    'fuenor/qfixgrep',
]
on_cmd = [
    'MemoNew',
    'MemoList',
    'MemoGrep',
]

[[plugins]]
repository = 'godlygeek/tabular'
on_cmd = 'Tabularize'

[[plugins]]
repository = 'deris/vim-rengbang'
on_cmd = [
    'RengBang',
    'RengBangUsePrev',
    'RengBangConfirm',
]

[[plugins]]
repository = 'lilydjwg/colorizer'
on_map = '<Plug>Colorizer'
on_cmd = [
    'ColorHighlight',
    'ColorClear',
    'ColorToggle',
]

[[plugins]]
repository = 'itchyny/calendar.vim'
on_cmd = 'Calendar'

# Unite sources ---------------------------------------------------------------

[[plugins]]
repository = 'Shougo/neomru.vim'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'Shougo/neossh.vim'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'Shougo/unite-help'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'Shougo/unite-outline'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'osyo-manga/unite-quickfix'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'ujihisa/unite-font'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'ujihisa/unite-colorscheme'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'rhysd/unite-codic.vim'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'pasela/unite-webcolorname'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'lambdalisue/unite-linephrase'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'joker1007/unite-pull-request'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'

[[plugins]]
repository = 'dameninngenn/unite-perldoc'
depends = 'Shougo/unite.vim'
on_source = 'unite.vim'


# Version controller system ---------------------------------------------------
[[plugins]]
repository = 'lambdalisue/vim-gita'
rev = 'alpha-3'
external_commands = 'git'
on_map  = '<Plug>(gita-'
on_func = ['gita#', 'hita#']
focus = 1
    [[plugins.on_cmd]]
    name = 'Gita'
    complete = 'customlist,gita#complete'
    [[plugins.on_cmd]]
    name = 'Hita'
    complete = 'customlist,hita#complete'

[[plugins]]
repository = 'lambdalisue/vim-gista'
on_func = 'gista#'
    [[plugins.on_cmd]]
    name = 'Gista'
    complete = 'customlist,gista#command#complete'

[[plugins]]
repository = 'lambdalisue/vim-gista-unite'
depends = ['lambdalisue/vim-gista', 'Shougo/unite.vim']
on_source = 'unite.vim'

[[plugins]]
repository = 'lambdalisue/vim-gista-ctrlp'
depends = ['lambdalisue/vim-gista', 'ctrlpvim/ctrlp.vim']
on_cmd = 'CtrlPGista'
on_func = 'ctrlp#gista#'

[[plugins]]
repository = 'cohama/agit.vim'
external_commands = 'git'
on_cmd    = ['Agit', 'AgitFile']
on_source = 'unite.vim'
focus = 1

[[plugins]]
repository = 'kmnk/vim-unite-giti'
depends = 'Shougo/unite.vim'
focus = 1
on_source = 'unite.vim'

[[plugins]]
repository = 'tpope/vim-fugitive'
external_commands = 'git'
augroup = 'fugitive'
on_cmd = [
    'Git', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge',
    'Gpull', 'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog',
    'Gllog', 'Gedit', 'Gsplit', 'Gvsplit', 'Gtabedit', 'Gpedit',
    'Gread', 'Gwrite', 'Gwq', 'Gdiff', 'Gsdiff', 'Gvdiff',
    'Gmove', 'Gremove', 'Gblame', 'Gbrowse',
]

[[plugins]]
repository = 'rafi/vim-unite-issue'
depends = [
    'Shougo/unite.vim',
    'mattn/webapi-vim',
    'tyru/open-browser.vim',
]
on_source = 'unite.vim'


# Syntax ----------------------------------------------------------------------
[[plugins]]
repository = 'hail2u/vim-css3-syntax'
on_ft = [
    'css', 'sass', 'scss', 'less', 'html',
]

[[plugins]]
repository = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repository = 'groenewege/vim-less'
on_ft = 'less'

[[plugins]]
repository = 'cakebaker/scss-syntax.vim'
on_ft = ['sass', 'scss']

[[plugins]]
repository = 'kchmck/vim-coffee-script'
on_ft = 'coffeescript'

[[plugins]]
repository = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repository = 'jQuery'
on_ft = ['javascript', 'coffeescript', 'typescript']

[[plugins]]
repository = 'jelera/vim-javascript-syntax'
on_ft = ['javascript', 'typescript']

[[plugins]]
repository = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']

[[plugins]]
repository = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repository = 'thinca/vim-ft-help_fold'
on_ft = 'help'

[[plugins]]
repository = 'vim-scripts/applescript.vim'
on_ft = 'applescript'

[[plugins]]
repository = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repository = 'vim-scripts/indentpython.vim'
on_ft = ['python', 'python3']

[[plugins]]
repository = 'vim-scripts/python_match.vim'
on_ft = ['python', 'python3']

[[plugins]]
repository = 'tmhedberg/SimpylFold'
on_ft = ['python', 'python3']

[[plugins]]
repository = 'vim-perl/vim-perl'
on_ft = 'perl'



# Specific --------------------------------------------------------------------
[[plugins]]
repository = 'LaTeX-Box-Team/LaTeX-Box'
external_commands = 'latexmk'
on_cmd = [
    'Latexmk',
    'LatexmkClean',
    'LatexmkStatus',
    'LatexmkStop',
    'LatexmkErrors',
    'LatexView',
    'LatexTOC',
    'LatexTOCToggle',
    'LatexLabels',
]
on_ft = ['tex', 'plaintex']

[[plugins]]
repository = 'tell-k/vim-autopep8'
external_commands = 'autopep8'
#build_commands = 'pip'
#build = 'pip install autopep8'
on_ft = ['python', 'python3']

[[plugins]]
repository = 'davidhalter/jedi-vim'
build_commands = 'git'
build = 'git submodule update --init'
on_source = 'vim-pyenv'
on_ft = ['python', 'python3']

[[plugins]]
repository = 'lambdalisue/vim-pyenv'
external_commands = 'pyenv'
on_cmd = ['PyenvActivate', 'PyenvDeactivate']
on_ft = ['python', 'python3']
focus = 1

[[plugins]]
repository = 'hotchpotch/perldoc-vim'
on_ft = 'perl'

[[plugins]]
repository = 'Quramy/tsuquyomi'
vim_version = '7.4'
depends = 'Shougo/vimproc.vim'
build_commands = 'npm'
build = 'npm install -g typescript'
on_ft = 'typescript'

[[plugins]]
repository = 'vim-pandoc/vim-pandoc'
on_ft = ['pandoc']

[[plugins]]
repository = 'kannokanno/previm'
depends = 'tyru/open-browser.vim'
on_cmd = 'PrevimOpen'


# Misc ------------------------------------------------------------------------
[[plugins]]
repository = 'cocopon/colorswatch.vim'
on_cmd = 'ColorSwatchGenerate'


# Vimscript development -------------------------------------------------------
[[plugins]]
repository = 'vim-jp/vital.vim'
lazy = 0

[[plugins]]
repository = 'osyo-manga/vital-over'

[[plugins]]
repository = 'osyo-manga/vital-unlocker'

[[plugins]]
repository = 'lambdalisue/vital-ArgumentParser'
lazy = 0

[[plugins]]
repository = 'lambdalisue/vital-VCS-Git'
lazy = 0

[[plugins]]
repository = 'lambdalisue/vital-Web-API-GitHub'
lazy = 0

[[plugins]]
repository = 'lambdalisue/vital-Vim-Buffer-Anchor'
lazy = 0

[[plugins]]
repository = 'lambdalisue/vital-Vim-Prompt'
lazy = 0

[[plugins]]
repository = 'lambdalisue/vital-Vim-Validate'
lazy = 0

[[plugins]]
repository = 'haya14busa/vital-power-assert'
depends = ['haya14busa/vital-vimlcompiler']
lazy = 0

[[plugins]]
repository = 'thinca/vim-themis'
on_ft = ['vim', 'vimspec']

[[plugins]]
repository = 'thinca/vim-prettyprint'
on_cmd = ['PP', 'PrettyPrint']
functions = ['PP', 'PrettyPrint']

[[plugins]]
repository = 'syngan/vim-vimlint'
depends = 'ynkdir/vim-vimlparser'

[[plugins]]
repository = 'LeafCage/laptime.vim'
functions = 'laptime#'
